version: '3'

env:
  RELEASE_NAME: sulfoxide-krypton

includes:
  util: tasks/Taskfile.util.yaml
  entei:topaz:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: topaz
  entei:amber:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: amber

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of Cert Manager
    cmds:
      - >-
        echo "karpenter: $(skopeo list-tags docker://public.ecr.aws/karpenter/karpenter 
        | jq -r '.Tags[]' 
        | grep -Eo '\b[0-9]+\.[0-9]+\.[0-9]+\b' 
        | sort -V 
        | tail -n 1
        )"
